services:
  - type: web
    name: myfilebot
    env: python
    startCommand: gunicorn app:app
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: CLOUD_NAME
        value: dq2ykb7hh
      - key: API_KEY
        value: 617275999532154
      - key: API_SECRET
        value: 40nV7iqLxbzdFK8mnE2PAXaOcbY
